### ISSUE TITLE
Deployment Stage Failure

### ISSUE THREAD

**Issue by MrJohnson-SixNinesIT** [lpm0073/cookiecutter-openedx-devops#19]
**Describe the bug**
This is a follow-up to a previous issue opened about a mongoDB failure when running the deployment Action:
https://github.com/lpm0073/cookiecutter-openedx-devops/issues/17

We've gone through our notes and what we have done, and we are fairly certain that we didn't use the mongo branch, and indeed, there is no MongoDB folders or files in our git repo. During the deployment build, we see this: 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/105312312/187452151-47138930-2fda-48db-a86f-5dc59626ffb8.png">

And here is the error we get from the logs:

```
File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/openedx/edx-platform/common/djangoapps/split_modulestore_django/migrations/0002_data_migration.py", line 26, in forwards_func
    for course_index in split_modulestore.db_connection.find_matching_course_indexes(force_mongo=True):
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 499, in _check_session_support
    self._select_servers_loop(
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: client is configured to connect to a replica set named '' but this node belongs to a set named 'None', Timeout: 30s, Topology Description: <TopologyDescription id: 630cef05ebbf63ea4e936254, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=ConfigurationError("client is configured to connect to a replica set named '' but this node belongs to a set named 'None'")>]>
```

Thanks for the quick responses. At this point, we may just run a terragrunt run-all destroy and have to start from scratch, as we just want to get something up and running as soon as possible.

So just to be sure everything is done right, we intend to do the following (assuming Environment_Name == Dev):

1. Run the CookieCutter command with our parameters (we shouldn't have to worry about MongoDB because it should now take a parameter who's default value is "No"
2. Navigate to the openedx_develops folder.
3. Push the code to our repo.
4. Add our credentials to the actions' secrets
5. Navigate to /terraform/environments/Dev/vpc
6. terragrunt apply
7. Navigate to /terraform/environments/Dev/kubernetes
8. terragrunt apply
9. Run into known build error
10. run terragrunt apply again
11. Navigate to /terraform/environments/Dev
12. terragrunt run-all apply

And just from those steps, we should be have all of our infrastructure created. 
Then, in our Actions (thanks for your response on our previous question about this)  we run the workflows in the following order:

1. Build Optional Containers
2. Build openedx container
3. Deploy {environment name}

Does this look accurate to you? Once again, thanks.

**Comment by lpm0073** [comment]
Thanks, the screen shot is helpful, and it provides new information that bears on your problem. Zeroing in row 2067, please note the following:

- It is a Kubernetes MongoDB *pod* that is stalling the deployment rather than anything to do with Github Actions.
- I occasionally run into this exact never-ending wait period when the EBS volume exists in an availability zone of the AWS data center in which you presently have no nodes (aka "EC2 instances) in a running state. What's happening is that the deployment need to mount the EBS volume to a pod running in a compute node, and that node needs to be running the same availability zone as the EBS volume itself (that is an AWS requirement rather than a k8s constraint).
- the easiest workaround is to a.) launch at least 1 EC2 instance in every availability zone. this will immediately allow the k8s deployment to complete
- alternatively you can inspect the PersistentVolumeClaims in your k8s cluster, find the one for MongoDB (it's probably exactly 5Gib in size) and then review the manifest to identify the VolumeID, which will looks something like the following: aws://us-east-2c/vol-0f2158b9c0ad158c8. Once you know the VolumeID then you can check the EBS console page from the AWS web site to verify the availability site in which it was created.

on an aside, this is one of the reasons that i created the new "remote MongoDB" option. All of the open edx platforms that i support are able to run reliably on 2 nodes when in an idle state, but AWS data centers all have 3 or more availability zones.

**Comment by MrJohnson-SixNinesIT** [comment]
Thanks for the response. After the wait from my first screenshot, things move on, but things ultimately still fail, and this is the real issue I believe:

![image](https://user-images.githubusercontent.com/105312312/187689473-95c9e253-0b33-4cfc-9d10-b4421fe768f3.png)

The logs associated with the above error, with the last line mentioning the client trying to connect to a replica set that is an empty string, but the node set being named "None" :

```
Traceback (most recent call last):
  File "./manage.py", line 106, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/openedx/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/openedx/venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/openedx/edx-platform/common/djangoapps/split_modulestore_django/migrations/0002_data_migration.py", line 26, in forwards_func
    for course_index in split_modulestore.db_connection.find_matching_course_indexes(force_mongo=True):
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 499, in _check_session_support
    self._select_servers_loop(
  File "/openedx/venv/lib/python3.8/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: client is configured to connect to a replica set named '' but this node belongs to a set named 'None', Timeout: 30s, Topology Description: <TopologyDescription id: 630f6081aa0f077ab0e96571, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=ConfigurationError("client is configured to connect to a replica set named '' but this node belongs to a set named 'None'")>]>
```
Thanks for explaining how this part works. We checked the PersistentVolumesClaims in the k8s cluster, and they are in the same availability zone as the nodes. In our case, us-east-1b:

![image](https://user-images.githubusercontent.com/105312312/187690589-12877272-1a7a-4597-99af-8ee5ae8dd925.png)

This is consistent with what you are saying about a wait period, and we aren't stuck in the never-ending wait. So it looks like we are good there.

**Comment by MrJohnson-SixNinesIT** [comment]
Looks like it was a tutor issue: https://discuss.openedx.org/t/mongodb-issue-with-nutmeg-2-and-tutor/8132/3

**Comment by lpm0073** [comment]
i posted a verbose comment to that effect yesterday. it vanished. very odd. yes, tutor bug. patched in this repo a couple of days ago.

**Comment by lpm0073** [comment]
closing this. i just released v1.0.4 which includes modifications related to resolution of this problem.

**Comment by lpm0073** [comment]
This is new and somewhat out of the ordinary. A bug surfaced in tutor a
couple of days ago. The short answer is that bumping tutor to 1.0.5
resolves the problem. More information about the bug here:
https://discuss.openedx.org/t/mongodb-issue-with-nutmeg-2-and-tutor/8132

I patched the Cookiecutter yester in the main branch so, if you want, you
can run the make.sh script and this will bump the version for you.

Otherwise, look for the tutor-version into in the "init" step of the
deployment workflow.

**Comment by MrJohnson-SixNinesIT** [comment]
Yeah we ended up making this change at that time and this particular issue went away. Thanks.
